### ISSUE TITLE
Debuff Icons Countdown

### ISSUE THREAD

**Issue by pgarneau** [shirsig/aurae#13]
Hey man! Love the work you did on this addon.

I modified my own "EnemyBuffTimersVanilla" to take into account PVP / PVE durations and certain DRs to fit my needs, but to be honest, I'd like to switch to a non "bootleg" addon. I was wondering if you could add support for having timers on the ememy debuff icons. Could either be number or the simple "clock" animation.

I'm just REALLY not a fan of bars.

Thanks

**Comment by shirsig** [comment]
Well, you're in luck, someone already did that: https://forum.elysium-project.org/index.php?showtopic=25081
It's based on aurae's old pvp tracking for both pvp and pve which makes more sense for target-only tracking.

Not sure if you're using the newest version of aurae but at this point it only tracks your own spells and only ccs and a few dots so I would consider using them both together. The purpose of the bars is not to look better than the debuff icons but to be shown even when not on your target because especially for ccs that's essential. If you e.g. sheep something you usually want to then target something else but still keep track of the sheep, so a timer on the debuff icon of the target frame doesn't help much.
