### ISSUE TITLE
Intercept Stun and Charge Stun DR

### ISSUE THREAD

**Issue by jaguardeer** [shirsig/aurae#16]
Warrior Charge and Intercept do not make a DR timer bar appear for me even though they are subject to DRs. I tried adding these into the addon but couldn't get it to work. I also tried installing DebuffTimers but the bars still don't appear.

**Comment by shirsig** [comment]
Yeah, they didn't make the cut when I changed the tracked spells. I think they're just too short, and since it only tracks the player's spells now their DR isn't interesting either so there's little point in showing a bar. If DebuffTimers doesn't show them that's a bug though I guess, but it's an independent addon now and not mine.

**Comment by jaguardeer** [comment]
Out of curiosity, should adding the correct entries in aurae_DR_CLASS, aurae_ACTION, and aurae_EFFECTS have added the DR timer?

**Comment by shirsig** [comment]
No, they would also have to be added to aurae_DR_CLASS.

**Comment by shirsig** [comment]
but there's another problem, the effect doesn't have the same name as the action so it doesn't work with the current system

**Comment by jaguardeer** [comment]
Got it. I saw the entries in DebuffTimers table but they seem to use the same system as yours so that might be why it doesn't work. Thanks for the insight and happy holidays :) Feel free to close
