### ISSUE TITLE
Mage Frostbite proc is not tracked

### ISSUE THREAD

**Issue by SamuliPolvi** [shirsig/aurae#24]
In Classic

**Comment by shirsig** [comment]
Yeah, currently only ccs resulting from actions are tracked except for the ones listed in the readme. The reason was that in vanilla the combat log event for applied debuffs was missing some important information which made them inaccurate. Classic doesn't have this limitation though so I will soon add them all.

**Comment by shirsig** [comment]
Could you tell me what the debuff resulting from frostbite is called please?

**Comment by SamuliPolvi** [comment]
The debuff is also called Frostbite

**Comment by shirsig** [comment]
thanks, added it.
