### ISSUE TITLE
add option to ignore multiple CCs of the same type

### ISSUE THREAD

**Issue by seren887** [shirsig/aurae#34]
When I pull 10 mobs, I get 10 "frost nova" CC bars. Can you add an option to limit bars shown to just 1? It clutters the screen. Thanks for your great work!

**Comment by shirsig** [comment]
This is due to the latest tracking improvement where tracking is based on the combat log directly and only spell rank and id are taken from the unit cast events. I remember someone complaining about only seeing one before, though I agree it's too much noise like this. I don't like the idea of limiting it to one randomly. I think I'm gonna add a setting to show aoe only for the target. Meanwhile you can use **/ccc ignore Frost Nova** if it bothers you.

**Comment by shirsig** [comment]
I uploaded a new version which only shows aoe on the target (or last target if no target) by default.
You can change the setting with **/ccc aoe target**, **/ccc aoe all**
