### ISSUE TITLE
Scatter shot + Freezing trap doesnt take DR into account

### ISSUE THREAD

**Issue by Elmuti** [shirsig/aurae#39]
When you use scatter shot, then freezing trap, the freezing trap duration shows up as 20 seconds when in fact its 10 seconds.

**Comment by shirsig** [comment]
Are you sure they share a dr? I thought it was only wyvern sting that is linked with freezing trap.

Afaik most or all cc has the same max duration in pvp as pve in classic, but often there is a chance for breaking early in pvp which increases the longer it lasts so it almost always lasts much less than the max duration (which ccc has to show anyway because it cannot know in advance when it breaks) Could it possibly be this?

**Comment by Elmuti** [comment]
They do for certain share DR, I duel on my hunter on a daily basis and can provide video proof if necessary. The trap duration is always exactly half after a scatter shot (unless heartbeat resists happen)

**Comment by Elmuti** [comment]
Alright, I have uploaded a [video](https://puu.sh/EXgyw/0ef668bc31.mp4)
2 regular freezing traps, following 2 freezing traps with a scatter opener.
Respective lengths of trap: 20, 20, 10, 10

**Comment by Elmuti** [comment]
Blizzard also confirmed this in blue post https://us.forums.blizzard.com/en/wow/t/hunter-beta-issues-update/223166

"Scatter Shot, Wyvern Sting, and Freezing Trap share diminishing returns"

**Comment by shirsig** [comment]
Thanks for your research. I fixed it.
