### ISSUE TITLE
[Suggestion / Request] One group of bars instead of three.

### ISSUE THREAD

**Issue by Theryk** [shirsig/aurae#6]
Hello! since today i have been using your addon (was using Chronometer) and i wonder if theres a easy way to only have one group of bars instead of 3 (just like Chronometer). I would like to have cc, debuff and buff all in one group of bars. If it is hard to implement, is there any chance for you to put it in your todo list as a optional feature in the future? thanks you!

**Comment by shirsig** [comment]
The layout with 3 bar groups was taken from ccwatch which this was originally based on. I'm not overly fond of it, but I'm worried it would get too high otherwise. Chronometer only tracks your own spells even in pvp afaik. aurae tracks all spells in combat log range and shows bars for every spell on recent targets so there are way more bars. I'll try it out when I have time.

**Comment by shirsig** [comment]
The newest version has only one group. It does seem to get a bit large though.

**Comment by Theryk** [comment]
Thanks you very much. It is possible to hide the dr bars too? it gets a bit large, yeah.

**Comment by shirsig** [comment]
Actually there have been a lot of changes. It only tracks the player's own spells now and also mostly only ccs, so there usually aren't many bars. I found that combining target and cross-target tracking doesn't work too well so now I'm trying to only track spells which are interesting for cross-target tracking and for others one could use renew's target frame timers: https://forum.elysium-project.org/index.php?showtopic=25081
